<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Log Data Report - {{ $area->name }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 20px;
            font-size: 10px;
        }
        .header {
            text-align: center;
            margin-bottom: 15px;
        }
        .header h1 {
            margin: 0;
            font-size: 18px;
            font-weight: bold;
        }
        .header p {
            margin: 3px 0;
            font-size: 9px;
        }
        .table-container {
            width: 100%;
            overflow-x: auto;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 15px;
            min-width: 600px; /* Ensure minimum width for readability */
        }
        th, td {
            border: 1px solid #ddd;
            padding: 4px; /* Reduced padding */
            text-align: left;
            font-size: 9px; /* Smaller font for compactness */
            white-space: nowrap; /* Prevent text wrapping */
        }
        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }
        .component-header {
            font-size: 12px;
            font-weight: bold;
            margin-top: 15px;
            margin-bottom: 5px;
        }
        .footer {
            text-align: center;
            font-size: 8px;
            margin-top: 15px;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Log Data Report - {{ $area->name }}</h1>
        <p>Area ID: {{ $area->AreaID }}</p>
        <p>Department: {{ $area->department->name ?? 'N/A' }}</p>
        <p>Generated on: {{ now()->format('Y-m-d H:i:s') }} WIB</p>
        <p>Generated by: {{ $user->name }}</p>
    </div>

    @foreach($components as $component)
        <div class="component-header">
            Component: {{ $component->name }} (ID: {{ $component->ComponentID }})
        </div>
        <div class="table-container">
            <table>
                <thead>
                    <tr>
                        <th style="width: 40px;">Log ID</th> <!-- Narrow width -->
                        <th style="width: 50px;">Value</th>
                        <th style="width: 90px;">Timestamp</th>
                        <th style="width: 80px;">Operator</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($component->logs as $log)
                        <tr>
                            <td>{{ $log->LogID }}</td>
                            <td>{{ $log->LogValue }}</td>
                            <td>{{ $log->LogTimestamp->format('Y-m-d H:i') }}</td>
                            <td>{{ $log->operator->name ?? 'Unknown' }}</td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="4" style="text-align: center;">No logs available for this component.</td>
                        </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    @endforeach

    <div class="footer">
        <p>Generated by Log Data System - {{ now()->format('Y') }}</p>
    </div>
</body>
</html>